#!/usr/bin/env bash

# Copyright 2019 The Grin Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script contains installation related code.

# Redeclare CI and VCP specific environment variables
# to make future migration to other providers easier.
readonly OS_NAME="${TRAVIS_OS_NAME}"

case "${OS_NAME}" in
    "linux")
        readonly CUDA_PGK="cuda-repo-ubuntu1604_10.0.130-1_amd64.deb"
        readonly CUDA_REPO="https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64"
        wget "${CUDA_REPO}/${CUDA_PGK}"
        sudo dpkg -i "${CUDA_PGK}"
        sudo apt-key adv --fetch-keys "${CUDA_REPO}/7fa2af80.pub"
        sudo apt-get update
        sudo apt-get install cuda
esac