[package]
name = "ocl_cuckatoo"
version = "1.0.2"
workspace = ".."

[dependencies]
blake2-rfc = "0.2"
byteorder = "1"
grin_miner_plugin = { path = "../plugin", version = "3.0.0-beta.1" }
libc = "0.2"
ocl = "0.19"
hashbrown = "0.7"

[lib]
name = "ocl_cuckatoo"
crate-type = ["cdylib", "rlib"]
